### ISSUE TITLE
No data for the last 10 days

### ISSUE THREAD

**Issue by ghost** [idandrd/israel-covid19-data#21]
There is no data for dates later than 2020-05-18, even thought the situation is still ongoing.

**Comment by kman3d** [comment]
Are you guys decided to stop updating? Please let us know, so we could look for other sources..

**Comment by ghost** [comment]
In the meantime, we can use [Worldometers](https://www.worldometers.info/coronavirus/country/israel/) (w/ data from Isreal's ministry of health) or [Our World in Data](https://ourworldindata.org/coronavirus/country/israel?country=~ISR) (w/ data from the European CDC). If you aren't going to update anymore, perhaps you could redirect visitors to one of those?

**Comment by liltruth** [comment]
Hi all,
We have stopped updating and thought what to do about it, since there were very small numbers from MOH in the past 2 weeks. Today we updated backwards and will consider redirecting to Worlometers from now on. We thought that by now MOH would publish their own dashboard and it has not happened, and we barely have time to volunteer and update the DB on an ongoing basis.
Ruth

**Comment by tsahi** [comment]
@liltruth  If I give you a console application that will push the Excel file the MOH publishes every day to your master/IsraelCOVID19.csv/xlsx, will you keep it it up to date?
